[net]
serial = "/dev/cu.usbserial-AQ03MLX2"
baud_rate = "1500000"
dtb_file = "os/StarryOS/configs/board/orangepi-5-plus.dtb"
shell_prefix = "root@starry:/root #"
shell_init_cmd = "echo NARROW_BEGIN; /home/orangepi/thp_narrow; echo FULL_RUN_DONE; sleep 1; sync; reboot -f"
success_regex = ["(?m)^FULL_RUN_DONE\\s*$"]
fail_regex = ["panicked at", "Unhandled( Synchronous)? [Ee]xception", "Kernel panic", "Synchronous Abort"]
timeout = 240
