//! RK3588 VOP2 display clock setup for a 1080p60 HDMI0 cold-init.
//!
//! For HDMI the VP0 pixel clock (`DCLK_VOP0`, 148.5 MHz) is generated by the
//! HDPTX0 PHY ROPLL and exposed as `clk_hdmiphy_pixel0`; the CRU only muxes that
//! external clock into VP0 and ungates the VOP root/leaf clocks. It does NOT
//! synthesise the 148.5 MHz — that is programmed in the HDPTX PHY driver. So
//! this is a small, deterministic register poke: select the PHY-pixel mux and
//! open the VOP gates. Values transcribed from mainline `clk-rk3588.c`.

use super::{Cru, consts::clk_sel112, consts::clkgate_con, consts::clksel_con};

/// `DCLK_VOP0` output-mux value selecting `clk_hdmiphy_pixel0` (the HDPTX0 PHY
/// pixel clock). Mux parents: 0=`dclk_vop0_src`, 1=`clk_hdmiphy_pixel0`,
/// 2=`clk_hdmiphy_pixel1`.
pub const DCLK0_VOP_SEL_HDMIPHY0: u32 = 1;

/// `CLKGATE_CON(52)` gate bits for the VOP path (a set bit = gated). For the
/// HDMI path the pixel clock comes from the PHY, so `dclk_vop0_src` (bit 10) is
/// intentionally not ungated — only the roots, hclk/aclk_vop and dclk_vop0.
mod gate52 {
    pub const ROOTS: u32 = 0xF; // aclk/aclk_low/hclk/pclk vop roots (bits 0..3)
    pub const HCLK_VOP: u32 = 1 << 8;
    pub const ACLK_VOP: u32 = 1 << 9;
    pub const DCLK_VOP0: u32 = 1 << 13;
    pub const VOP_HDMI_MASK: u32 = ROOTS | HCLK_VOP | ACLK_VOP | DCLK_VOP0;
}

/// `CLKSEL_CON(115)` `aclk_vop_sub_src` mux: bit 9, 0 = `aclk_vop_root`.
const ACLK_VOP_SUB_SRC_ROOT_BIT: u32 = 1 << 9;

impl Cru {
    /// Bring up the VOP2 clocks for a VP0→HDMI0 1080p60 cold-init: point the
    /// `DCLK_VOP0` output mux at the HDPTX0 PHY pixel clock and ungate the VOP
    /// root + hclk/aclk + dclk_vop0 gates. Idempotent (hiword-masked writes).
    ///
    /// Prerequisite: the HDPTX PHY must already have registered/locked its
    /// pixel clock (otherwise the mux selects a dead parent). The 148.5 MHz rate
    /// itself is set in the PHY, not here.
    pub fn vop_hdmi0_clocks_setup(&mut self) {
        // Route DCLK_VOP0 to clk_hdmiphy_pixel0.
        self.clrsetreg(
            clksel_con(112),
            clk_sel112::DCLK0_VOP_SEL_MASK,
            DCLK0_VOP_SEL_HDMIPHY0 << clk_sel112::DCLK0_VOP_SEL_SHIFT,
        );
        // aclk_vop_sub_src = aclk_vop_root.
        self.clrreg(clksel_con(115), ACLK_VOP_SUB_SRC_ROOT_BIT);
        // Ungate the VOP roots + hclk/aclk + dclk_vop0 (defensive: a headless
        // cold boot may leave the non-critical VOP roots gated).
        self.clrreg(clkgate_con(52), gate52::VOP_HDMI_MASK);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dclk_vop0_mux_word_selects_hdmiphy0() {
        // The hiword-masked clrsetreg word for the mux write == 0x0180_0080
        // (bits[8:7]=1). clr = mask (0x180), set = 1<<7 (0x80).
        let clr = clk_sel112::DCLK0_VOP_SEL_MASK;
        let set = DCLK0_VOP_SEL_HDMIPHY0 << clk_sel112::DCLK0_VOP_SEL_SHIFT;
        assert_eq!(clr, 0x180);
        assert_eq!(set, 0x80);
        assert_eq!(((clr | set) << 16) | set, 0x0180_0080);
    }

    #[test]
    fn vop_gate_mask_matches_mainline() {
        // roots(0xF) | hclk(bit8) | aclk(bit9) | dclk_vop0(bit13) = 0x230F.
        assert_eq!(gate52::VOP_HDMI_MASK, 0x230F);
        // clrreg word ungates them: mask << 16.
        assert_eq!(gate52::VOP_HDMI_MASK << 16, 0x230F_0000);
    }

    #[test]
    fn con_offsets() {
        // CLKSEL_CON(112) = 112*4 + 0x300 = 0x4C0; CLKGATE_CON(52) = 52*4 + 0x800 = 0x8D0.
        assert_eq!(clksel_con(112), 0x4C0);
        assert_eq!(clkgate_con(52), 0x8D0);
    }
}
